### ISSUE TITLE
测试爬取段子页面时报错

### ISSUE THREAD

**Issue by OctopusLian** [laboratory-coding/JokeCrawler#1]
```
请输入起始页（>=1）: 1
请输入终止页（>=起始页）: 5
准备爬取第1到5页的网址
正在爬取 1个网页:http://www.pengfu.com/xiaohua_1.html
Http get err =  Get http://www.pengfu.com/xiaohua_1.html: dial tcp 74.86.228.110:80: i/o timeout
正在爬取 2个网页:http://www.pengfu.com/xiaohua_2.html
resp read body err =  EOF
panic: regexp: Compile(`<h1 class="dp-b"><a href="(?s:(.*?)"`): error parsing regexp: missing closing ): `<h1 class="dp-b"><a href="(?s:(.*?)"`

goroutine 1 [running]:
regexp.MustCompile(0x6f1554, 0x24, 0xc0000e6000)
	/usr/local/go/src/regexp/regexp.go:272 +0x159
main.SpiderPage(0x2)
	/home/zoctopus/code/go/src/github.com/laboratory-coding/JokeCrawler/main.go:91 +0x1dc
main.DoWork(0x1, 0x5)
	/home/zoctopus/code/go/src/github.com/laboratory-coding/JokeCrawler/main.go:120 +0xf3
main.main()
	/home/zoctopus/code/go/src/github.com/laboratory-coding/JokeCrawler/main.go:132 +0x1b5
```

**Comment by OctopusLian** [comment]
也许和这个有关  

```go
	//解析表达式
	re := regexp.MustCompile(`<h1 class="dp-b"><a href="(?s:(.*?)"`)
	fmt.Println("re = ", re)
	if re == nil {
		fmt.Println("regexp compile failed")
		return
	}
```

**Comment by OctopusLian** [comment]
## 解决  

- timeout是网速不佳造成的超时；  
- panic是因为在解析正则表达式的时候少了一个 )
